version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
      - dependency-name: "govuk-frontend"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"