#' Service navigation
#'
#' @description
#' Service navigation component consistent with the
#' [GDS service navigation](https://design-system.service.gov.uk/components/service-navigation/). # nolint
#'
#' **Note:** This component uses a hardcoded element ID
#' for the navigation list and mobile menu toggle. Using
#' multiple `service_navigation()` instances on the same
#' page will cause ID conflicts and the mobile menu toggle
#' may not work correctly.
#'
#' @param links A vector of actionLinks to be added to the
#' service navigation. inputIDs are auto-generated by
#' lowercasing the link text and replacing all
#' non-alphanumeric characters with underscores, e.g.
#' "Overview page" becomes `overview_page`. For precise
#' control over inputIDs, supply a named vector where names
#' are the page titles and values are the inputIDs.
#' @param service_name An optional character string
#' containing the service name to be displayed in the
#' navigation bar
#' @param auto_page_title Logical. When `TRUE` (the default),
#' the browser tab title is updated to match the active nav
#' link whenever the user navigates — both by clicking a
#' link and via `update_service_navigation()`. Set to `FALSE`
#' to opt out and manage the page title yourself. Keeping
#' the title in sync with the visible page is a GOV.UK
#' Design System recommendation for accessibility.
#' @param page_title_suffix Optional character string
#' appended to the page title in the format
#' `"<link text> | <suffix>"` — typically the service name.
#' Only used when `auto_page_title = TRUE`. For finer
#' control (e.g. when a page heading differs from its nav
#' link label), call [update_page_title()] from your server
#' code.
#'
#' @returns Shiny tag object
#' @family Govstyle navigation
#' @export
#'
#' @examples
#' ui <- shiny::fluidPage(
#'   shinyGovstyle::header("Title", "Secondary heading"),
#'   shinyGovstyle::service_navigation(
#'      c("Summary data", "Detailed stats 1", "User guide")
#'   ),
#'   bslib::navset_hidden(
#'      id = "main_panels",
#'      bslib::nav_panel(
#'        "summary_data",
#'        shiny::tags$h2("Summary data")
#'      ),
#'      bslib::nav_panel(
#'        "detailed_stats_1",
#'        shiny::tags$h2("Detailed stats 1")
#'      ),
#'      bslib::nav_panel(
#'        "user_guide",
#'        shiny::tags$h2("User guide")
#'      )
#'    ),
#'    shinyGovstyle::footer(full = TRUE)
#' )
#'
#' server <- function(input, output, session) {
#'   observeEvent(
#'     input$summary_data,
#'     bslib::nav_select("main_panels", "summary_data")
#'   )
#'   observeEvent(
#'     input$detailed_stats_1,
#'     bslib::nav_select("main_panels", "detailed_stats_1")
#'   )
#'   observeEvent(
#'     input$user_guide,
#'     bslib::nav_select("main_panels", "user_guide")
#'   )
#' }
#'
#' if (interactive()) shiny::shinyApp(ui = ui, server = server)
service_navigation <- function(
  links,
  service_name = NULL,
  auto_page_title = TRUE,
  page_title_suffix = NULL
) {
  if (is.null(links) || length(links) == 0) {
    stop("links must be a non-empty character vector")
  }
  if (is.null(names(links))) {
    link_names <- links
  } else {
    link_names <- names(links)
    link_names[link_names == ""] <- links[link_names == ""]
  }
  navigation <- shiny::tags$section(
    `aria-label` = "Service information",
    class = "govuk-service-navigation",
    `data-module` = "govuk-service-navigation",
    `data-auto-page-title` = if (isTRUE(auto_page_title)) "true",
    `data-page-title-suffix` = if (
      isTRUE(auto_page_title) &&
        !is.null(page_title_suffix) &&
        nzchar(page_title_suffix)
    ) {
      page_title_suffix
    },
    shiny::tags$div(
      class = "govuk-width-container",
      shiny::tags$div(
        class = "govuk-service-navigation__container",
        if (!is.null(service_name)) {
          shiny::tags$span(
            class = "govuk-service-navigation__service-name",
            shiny::tags$a(
              href = "#",
              class = "govuk-service-navigation__link",
              service_name
            )
          )
        },
        shiny::tags$nav(
          `aria-label` = "Menu",
          class = "govuk-service-navigation__wrapper",
          shiny::tags$button(
            type = "button",
            class = paste(
              "govuk-service-navigation__toggle",
              "govuk-js-service-navigation-toggle"
            ),
            `aria-controls` = "navigation",
            hidden = TRUE,
            "Menu"
          ),
          shiny::tags$ul(
            class = "govuk-service-navigation__list",
            id = "navigation",
            mapply(
              service_nav_link,
              links,
              link_names,
              SIMPLIFY = FALSE,
              USE.NAMES = FALSE
            )
          )
        )
      )
    )
  )
  attachDependency(navigation, "service_navigation") # nolint
}


#' Update the active item in a service navigation component
#'
#' @description
#' Sends a message to the browser to update the highlighted active item in the
#' service navigation bar.
#'
#' **When you need this function:** when navigation is triggered
#' programmatically — for example, via a next / back button or a footer link
#' that points to a main page. In those cases the nav link itself is not
#' clicked, so the JavaScript binding does not fire and the active state does
#' not update automatically. Call `update_service_navigation()` alongside
#' your tab-switching call to keep them in sync.
#'
#' **When you don't need this function:** when the user clicks a service
#' navigation link directly. The JavaScript binding updates the active state
#' automatically, so you only need to switch the tab panel in your
#' `observeEvent()`.
#'
#' @param session The Shiny session object
#' @param inputId The inputId of the service navigation link to set as active
#'
#' @returns NULL, called for side effects
#' @family Govstyle navigation
#' @export
#'
#' @examples
#' # Works the same with shiny::tabsetPanel() + shiny::updateTabsetPanel().
#' ui <- shiny::fluidPage(
#'   shinyGovstyle::service_navigation(c("Page one", "Page two")),
#'   bslib::navset_hidden(
#'     id = "tabs",
#'     bslib::nav_panel("page_one", shiny::actionButton("next_btn", "Next")),
#'     bslib::nav_panel("page_two", "Page two content")
#'   )
#' )
#'
#' server <- function(input, output, session) {
#'   # Nav link clicked — JS handles the active state, just switch the panel.
#'   shiny::observeEvent(input$page_two, {
#'     bslib::nav_select("tabs", "page_two")
#'   })
#'
#'   # Programmatic navigation — the nav link is not clicked, so call
#'   # update_service_navigation() explicitly.
#'   shiny::observeEvent(input$next_btn, {
#'     bslib::nav_select("tabs", "page_two")
#'     shinyGovstyle::update_service_navigation(session, "page_two")
#'   })
#' }
#'
#' if (interactive()) shiny::shinyApp(ui = ui, server = server)
update_service_navigation <- function(
  session,
  inputId # nolint: object_name_linter.
) {
  session$sendCustomMessage(
    "update_service_navigation",
    inputId
  )
}


#' Auto-wire service navigation links to tabset panels
#'
#' @description
#' Sets up one observer per nav link that switches the corresponding tab
#' panel when the link is clicked. Eliminates the per-link
#' `observeEvent()` boilerplate that multi-page apps would otherwise need.
#'
#' Call once in your server function, after [service_navigation()] has been
#' added to the UI. The active nav highlight and (when
#' `auto_page_title = TRUE`) the browser tab title are already handled
#' client-side, so no additional wiring is needed.
#'
#' @param session The Shiny session object
#' @param tabset_id The `id` of the `shiny::tabsetPanel()` or
#'   `bslib::navset_hidden()` to switch
#' @param link_to_panel A character vector mapping nav link inputIds to
#'   tab panel values. Pass a **named** vector when inputIds differ from
#'   panel values (names = inputIds, values = panel values). Pass an
#'   **unnamed** vector as shorthand for the 1:1 case — each element is
#'   used as both the nav inputId and the panel value.
#'
#' @returns NULL, called for side effects
#' @family Govstyle navigation
#' @export
#'
#' @examples
#' ui <- shiny::fluidPage(
#'   shinyGovstyle::service_navigation(
#'     c(sn_summary = "Summary", sn_detail = "Detail")
#'   ),
#'   bslib::navset_hidden(
#'     id = "tabs",
#'     bslib::nav_panel("summary", "Summary content"),
#'     bslib::nav_panel("detailed_data", "Detail content")
#'   )
#' )
#'
#' server <- function(input, output, session) {
#'   # Nav inputIds differ from panel values
#'   shinyGovstyle::service_navigation_server(
#'     session,
#'     tabset_id = "tabs",
#'     link_to_panel = c(
#'       sn_summary = "summary",
#'       sn_detail = "detailed_data"
#'     )
#'   )
#'
#'   # Or, when inputIds match panel values exactly:
#'   # shinyGovstyle::service_navigation_server(
#'   #   session,
#'   #   tabset_id = "tabs",
#'   #   link_to_panel = c("summary", "detailed_data")
#'   # )
#' }
#'
#' if (interactive()) shiny::shinyApp(ui = ui, server = server)
service_navigation_server <- function(
  session,
  tabset_id, # nolint: object_name_linter.
  link_to_panel
) {
  if (is.null(link_to_panel) || length(link_to_panel) == 0) {
    stop("link_to_panel must be a non-empty character vector")
  }
  stopifnot(is.character(link_to_panel))
  if (is.null(names(link_to_panel))) {
    names(link_to_panel) <- link_to_panel
  } else {
    blanks <- names(link_to_panel) == ""
    names(link_to_panel)[blanks] <- link_to_panel[blanks]
  }

  input <- session$input
  lapply(seq_along(link_to_panel), function(i) {
    input_id <- names(link_to_panel)[i]
    panel <- link_to_panel[[i]]
    shiny::observeEvent(
      input[[input_id]],
      shiny::updateTabsetPanel(session, tabset_id, selected = panel),
      ignoreInit = TRUE
    )
  })
  invisible(NULL)
}


#' Create a service navigation link for use in `service_navigation()` function
#'
#' @param link Character string containing either link text or url
#' @param link_name Name of a link where a URL has been provided in link_text
#'
#' @returns HTML tag list item
#' @noRd
#' @keywords internal
#' @examples
#' # Named internal link
#' shinyGovstyle:::service_nav_link("cookie_statement", "Cookies")
service_nav_link <- function(
  link,
  link_name
) {
  stopifnot(!is.null(link_name), nzchar(link_name))
  shiny::tags$li(
    class = "govuk-service-navigation__item",
    shiny::actionLink(
      class = "govuk-service-navigation__link",
      inputId = tolower(gsub("[^a-zA-Z0-9]", "_", link)),
      label = link_name
    )
  )
}
