on:
  push:
    branches:
      - main

name: Showcase app deploy

jobs:
  deployShiny:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Load package
        shell: Rscript {0}
        run: |
          devtools::load_all()

      - name: Install rsconnect
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::install("rsconnect")

      - name: Push to shinyapps.io
        run: >
          Rscript
          -e "rsconnect::setAccountInfo(name = 'department-for-education', token = '${{secrets.SHINYAPPS_TOKEN}}', secret = '${{secrets.SHINYAPPS_SECRET}}')"
          -e "shiny_app <- run_example()"
          -e "rsconnect::deployApp(shiny_app, forceUpdate = TRUE)"
